name: ci
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - develop

jobs:
  build:
    # Job name is Greeting
    name: cij
    # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: npm --version
