name: ci
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - develop

jobs:
  build:
    # Job name is Greeting
    name: cij
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: check out
        run: git checkout develop